Page.delete_all
root = Page.create!(:name => 'Root')
account = Page.create!(:name => 'Account', :proposed_parent_id => root, :controller => 'users', :action => 'show', :parameters => 'current_user')
users = Page.create!(:name => 'Users', :proposed_parent_id => root, :controller => 'admin/users', :action => 'index')
list_users = Page.create!(:name => 'List', :proposed_parent_id => users, :controller => 'admin/users', :action => 'index')
new_user = Page.create!(:name => 'New', :proposed_parent_id => users, :controller => 'admin/users', :action => 'new')
pages = Page.create!(:name => 'Pages', :proposed_parent_id => root, :controller => 'admin/pages', :action => 'index')
list_pages = Page.create!(:name => 'List', :proposed_parent_id => pages, :controller => 'admin/pages', :action => 'index')
new_page = Page.create!(:name => 'New', :proposed_parent_id => pages, :controller => 'admin/pages', :action => 'new')
vacancies = Page.create!(:name => 'Vacancies', :proposed_parent_id => root, :controller => 'admin/vacancies', :action => 'index')
list_vacancies = Page.create!(:name => 'List', :proposed_parent_id => vacancies, :controller => 'admin/vacancies', :action => 'index')
new_vacancy = Page.create!(:name => 'New', :proposed_parent_id => vacancies, :controller => 'admin/vacancies', :action => 'new')
edit_vacancy = Page.create!(:name => 'Edit', :proposed_parent_id => list_vacancies, :controller => 'admin/vacancies', :action => 'edit', :parameters => 'id')
