development: &local
    site_name: Orbis Resourcing
    site_domain: "localhost:3000"
    site_title: Orbis Resourcing
    site_tag:  Orbis resourcing tag
    admin_email: damianajones@yahoo.co.uk
    accounts_email: damianajones@yahoo.co.uk
    info_email: damianajones@yahoo.co.uk
    dev_email: damianajones@yahoo.co.uk

test:
  <<: *local
  site_domain: "localhost:3000"

cucumber:
  <<: *local
  site_domain: "localhost:3000"

production:
  <<: *local
  site_domain: www.orbisresourcing.com

