development: &local
    site_name: Orbis Resourcing
    site_domain: "localhost:3000"
    site_title: Orbis Resourcing
    site_tag:  Orbis resourcing tag
    admin_email: admin@example.com
    accounts_email: accounts@example.com
    info_email: info@example.com
    dev_email: damianajones@yahoo.co.uk

test:
  <<: *local
  site_domain: "localhost:3000"

cucumber:
  <<: *local
  site_domain: "localhost:3000"

production:
  <<: *local
  site_domain: www.orbisresourcing.com

