development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: orbis_development
  pool: 5
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: orbis_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: orbis_production
  pool: 5
  username: root
  password:
  host: localhost

cucumber:
  <<: *TEST
