development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: orbis_development
  pool: 5
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: orbis_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: db21636_orbis_prod
  pool: 5
  username: orbis
  password: orgone642
  host: localhost

cucumber:
  <<: *TEST
