cwd: /var/www/vhosts/ruralandweb.com/subdomains/orbis/current
log_file: log/mongrel.log
port: "4000"
environment: production
address: 127.0.0.1
pid_file: /var/run/mongrel_cluster/mongrel.pid

servers: 3
